### ISSUE TITLE
Removal of pub binary breaks installation script in the formula

### ISSUE THREAD

**Issue by mraleph** [dart-lang/homebrew-dart#91] opened 2021-07-16 13:24 UTC
```
brew upgrade dart
==> Upgrading 1 outdated package:
dart-lang/dart/dart HEAD -> HEAD
==> Upgrading dart-lang/dart/dart
  HEAD -> HEAD

==> Downloading https://storage.googleapis.com/dart-archive/channels/dev/release/2.14.0-321.0.dev/sdk/dartsdk-macos-x64-release.zip
######################################################################## 100.0%
Warning: Your Xcode (12.4) is outdated.
Please update to Xcode 12.5 (or delete it).
Xcode can be updated from the App Store.

Error: An exception occurred within a child process:
  Errno::EACCES: Permission denied @ rb_sysopen - /Users/vegorov/homebrew/Cellar/dart/HEAD/bin/pub
```

**Comment by athomas** [comment] 2021-07-20 09:40
Strange, the pub binary is still in that zip file. I've a PR to see if I can reproduce this on GitHub Actions:
https://github.com/dart-lang/homebrew-dart/pull/92

Could be that this is an artifact of the recent re-organization of the files in the tap.

**Comment by athomas** [comment] 2021-07-20 13:09
On a fresh install, `brew install dart --HEAD` worked for me.

**Comment by athomas** [comment] 2021-08-06 09:24
I'm going to close this as won't fix because I can't reproduce the issue and there is a workaround (uninstall, untap then tap and install again).

**Closed by athomas** 2021-08-06 09:24 UTC

**Comment by mraleph** [comment] 2021-08-09 07:28
I can't reproduce it either anymore unfortunately.
